#
# Copyright 2011 Freescale Semiconductor, Inc.
# (C) Copyright 2001-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= tlabp204x.o
obj-y += cpld.o
obj-y	+= ddr.o
obj-y	+= law.o
obj-y	+= pci.o
obj-y	+= tlb.o
obj-y	+= cpld_spi.o
obj-y	+= mvswitch.o
obj-y	+= eth.o
obj-y	+= zl30155.o
